# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# kitty.conf

font_family      JetBrainsMono Nerd Font
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

font_size 14.0

disable_ligatures never

scrollback_lines 9000
scrollback_indicator_opacity 1.0
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
wheel_scroll_multiplier 5.0
wheel_scroll_min_lines 1

mouse_hide_wait 3.0

url_color #0087bd
url_style curly
detect_urls yes
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

copy_on_select yes
strip_trailing_spaces always

repaint_delay 10
sync_to_monitor yes
window_padding_width 8
hide_window_decorations no
dynamic_background_opacity yes
background_opacity 0.9

cursor #cccccc
cursor_text_color #111111
cursor_shape block

term xterm-kitty
shell /usr/bin/fish

# keys
kitty_mod ctrl+shift

map ctrl+c copy_to_clipboard
map ctrl+v  paste_from_clipboard
map kitty_mod+s  paste_from_selection